-- Staging: thin, typed view over the warehouse fact. Marts never read warehouse.* directly.
select
    order_key,
    order_id,
    customer_key,
    customer_id,
    region_key,
    region_code,
    order_date_key,
    order_ts,
    order_date,
    order_month,
    status,
    channel,
    currency,
    coupon_code,
    order_total_local,
    order_total_usd,
    gross_amount_usd,
    discount_usd,
    lines_total_usd,
    lines_reconciled,
    item_count,
    total_quantity,
    paid_at,
    captured_amount_usd,
    refunded_amount_usd,
    failed_payment_attempts,
    is_cancelled,
    is_returned,
    is_revenue,
    customer_order_seq,
    days_since_prev_order,
    is_first_order,
    updated_at,
    _loaded_at as loaded_at
from {{ source('warehouse', 'fact_orders') }}
