select
    order_item_key,
    order_item_id,
    order_key,
    order_id,
    product_key,
    product_id,
    category_key,
    supplier_key,
    customer_key,
    region_key,
    order_date,
    order_month,
    order_ts,
    status,
    quantity,
    unit_price_usd,
    discount_pct,
    line_total_usd,
    unit_cost_usd,
    line_cost_usd,
    gross_margin_usd,
    is_revenue,
    is_returned,
    _loaded_at as loaded_at
from {{ source('warehouse', 'fact_order_items') }}
