"""Seeded random helpers and vocabularies used by all generators."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date, datetime, timedelta

import numpy as np
import pandas as pd

SYNTHETIC_NOTICE = "SYNTHETIC DATA - generated by DataForge; does not describe real people or companies."

FIRST_NAMES = [
    "Aarav",
    "Amelia",
    "Ana",
    "Arjun",
    "Ayesha",
    "Ben",
    "Carlos",
    "Chloe",
    "Daniel",
    "Diego",
    "Elena",
    "Emma",
    "Fatima",
    "Felix",
    "Grace",
    "Hana",
    "Hugo",
    "Isla",
    "Ivan",
    "Jade",
    "Jonas",
    "Kai",
    "Kira",
    "Leo",
    "Lina",
    "Lucas",
    "Maya",
    "Mateo",
    "Mia",
    "Nadia",
    "Noah",
    "Olivia",
    "Omar",
    "Priya",
    "Rafael",
    "Riya",
    "Sara",
    "Sofia",
    "Tariq",
    "Theo",
    "Uma",
    "Victor",
    "Wei",
    "Yara",
    "Yusuf",
    "Zara",
    "Zoe",
    "Ravi",
    "Nina",
    "Ethan",
]
LAST_NAMES = [
    "Ahmed",
    "Alvarez",
    "Anderson",
    "Bauer",
    "Bennett",
    "Brown",
    "Chen",
    "Costa",
    "Das",
    "Dubois",
    "Fischer",
    "Garcia",
    "Gupta",
    "Hansen",
    "Hernandez",
    "Ibrahim",
    "Ito",
    "Jensen",
    "Khan",
    "Kim",
    "Kowalski",
    "Kumar",
    "Lee",
    "Lopez",
    "Martin",
    "Mehta",
    "Miller",
    "Moreau",
    "Nakamura",
    "Nguyen",
    "Novak",
    "Okafor",
    "Patel",
    "Pereira",
    "Rossi",
    "Santos",
    "Schmidt",
    "Sharma",
    "Silva",
    "Singh",
    "Smith",
    "Tanaka",
    "Torres",
    "Walker",
    "Wang",
    "Weber",
    "Wilson",
    "Yamamoto",
    "Zhang",
    "Zimmerman",
]
EMAIL_DOMAINS = ["example.com", "example.org", "example.net", "mail.example", "inbox.example"]
STREET_WORDS = ["Maple", "Cedar", "Harbor", "Summit", "Willow", "Orchard", "Ridge", "Meadow", "Lake", "Park"]
STREET_TYPES = ["St", "Ave", "Rd", "Blvd", "Ln", "Way"]

PRODUCT_ADJECTIVES = [
    "Classic",
    "Pro",
    "Ultra",
    "Compact",
    "Eco",
    "Premium",
    "Essential",
    "Smart",
    "Rapid",
    "Fusion",
    "Nordic",
    "Urban",
    "Studio",
    "Prime",
    "Lite",
    "Max",
    "Aero",
    "Terra",
    "Vivid",
    "Quiet",
]
BRANDS = [
    "Northwind",
    "Brightline",
    "Kestrel",
    "Oakmere",
    "Solvei",
    "Halcyon",
    "Marrow",
    "Quillon",
    "Tessera",
    "Vantage",
    "Ardent",
    "Lumo",
    "Pinecrest",
    "Ridgeway",
    "Cobalt",
    "Ember",
    "Fjord",
    "Granite",
    "Juniper",
    "Sable",
]
CARRIERS = ["SwiftParcel", "GlobeFreight", "NorthStar Logistics", "BlueRoute", "ParcelHive"]
CHANNELS = ["web", "mobile_app", "marketplace", "store"]
PAYMENT_METHODS = ["credit_card", "debit_card", "wallet", "bank_transfer", "cash_on_delivery"]
ORDER_STATUSES = ["placed", "paid", "shipped", "delivered", "cancelled", "returned"]
INVENTORY_EVENT_TYPES = ["receipt", "shipment", "adjustment", "return", "stock_count"]
SHIPPING_EVENT_TYPES = [
    "label_created",
    "picked_up",
    "in_transit",
    "out_for_delivery",
    "delivered",
    "delivery_exception",
    "returned",
]


@dataclass
class GenConfig:
    seed: int = 20240101
    scale: float = 1.0
    start_date: date = date(2024, 1, 1)
    end_date: date = date(2025, 12, 31)
    # Batch boundaries (inclusive end dates). Records are assigned to the first batch whose
    # end date >= the record's business timestamp. The last batch also collects late updates.
    batches: list[date] = field(default_factory=lambda: [date(2025, 11, 30), date(2025, 12, 31)])
    defect_rate_multiplier: float = 1.0

    @property
    def n_customers(self) -> int:
        return int(20_000 * self.scale)

    @property
    def n_products(self) -> int:
        return int(5_000 * self.scale)

    @property
    def n_orders(self) -> int:
        return int(100_000 * self.scale)

    @property
    def n_suppliers(self) -> int:
        return max(20, int(150 * min(self.scale, 1.0)))

    @property
    def n_warehouses(self) -> int:
        return 12

    @property
    def days(self) -> int:
        return (self.end_date - self.start_date).days + 1


class Rng:
    """Thin wrapper over numpy Generator with convenience helpers.

    Each generator derives its own child stream (`rng.child("orders")`) so adding a new
    generator never changes the output of an existing one.
    """

    def __init__(self, seed: int, stream: str = "root"):
        self.seed = seed
        self.stream = stream
        # Python's hash() is salted per process for str -> use a stable FNV-1a hash instead
        h = _stable_hash(f"{seed}:{stream}")
        self.g = np.random.default_rng(h)

    def child(self, stream: str) -> Rng:
        return Rng(self.seed, f"{self.stream}/{stream}")

    def choice(self, seq, size=None, p=None, replace=True):
        return self.g.choice(seq, size=size, p=p, replace=replace)

    def ints(self, low, high, size=None):
        return self.g.integers(low, high, size=size)

    def floats(self, low, high, size=None):
        return self.g.uniform(low, high, size=size)

    def bool_mask(self, n: int, rate: float) -> np.ndarray:
        return self.g.random(n) < rate

    def sample_idx(self, n: int, k: int) -> np.ndarray:
        k = min(k, n)
        return self.g.choice(n, size=k, replace=False) if k > 0 else np.array([], dtype=int)

    def pareto_weights(self, n: int, shape: float = 1.2) -> np.ndarray:
        w = self.g.pareto(shape, size=n) + 1.0
        return w / w.sum()

    def timestamps(self, start: date, end: date, n: int, trend: float = 0.0) -> pd.Series:
        """Random UTC timestamps between start/end with optional linear growth trend."""
        days = (end - start).days + 1
        base = self.g.random(n)
        if trend:
            # Bias towards later dates when trend > 0 (approx linear density growth)
            base = np.where(self.g.random(n) < trend, np.sqrt(base), base)
        day_offsets = np.floor(base * days).astype(int)
        seconds = self.g.integers(0, 86400, size=n)
        origin = datetime(start.year, start.month, start.day)
        return pd.Series(
            pd.to_datetime(origin)
            + pd.to_timedelta(day_offsets, unit="D")
            + pd.to_timedelta(seconds, unit="s")
        )


def _stable_hash(s: str) -> int:
    h = 2166136261
    for ch in s.encode():
        h ^= ch
        h = (h * 16777619) % (2**32)
    return h


def make_ids(prefix: str, n: int, width: int = 7, start: int = 1) -> np.ndarray:
    return np.array([f"{prefix}-{i:0{width}d}" for i in range(start, start + n)])


def parse_iso(s: pd.Series) -> pd.Series:
    """ISO-8601 strings (trailing Z) -> naive UTC timestamps."""
    return pd.to_datetime(s, errors="coerce", utc=True).dt.tz_localize(None)


def to_iso(ts: pd.Series) -> pd.Series:
    return ts.dt.strftime("%Y-%m-%dT%H:%M:%SZ")


def add_days(ts: pd.Series, days: np.ndarray, hours: np.ndarray | None = None) -> pd.Series:
    out = ts + pd.to_timedelta(days, unit="D")
    if hours is not None:
        out = out + pd.to_timedelta(hours, unit="h")
    return out


def cutoff_ts(d: date) -> pd.Timestamp:
    return pd.Timestamp(d) + timedelta(days=1) - timedelta(seconds=1)
