"""Raw-file writers for each source format, including parse-level malformations."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pandas as pd

from .base import Rng
from .shipping import render_log_line


def write_csv(df: pd.DataFrame, path: Path) -> int:
    path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(path, index=False, lineterminator="\n")
    return len(df)


def write_json_document(doc: dict[str, Any], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=None, default=str)


def write_ndjson(
    records: list[dict[str, Any]], path: Path, rng: Rng, malformed_rate: float = 0.0
) -> tuple[int, int]:
    """Writes one JSON object per line. A seeded fraction of lines is truncated or
    replaced with garbage to simulate a flaky producer. Returns (rows, malformed)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    r = rng.child(f"ndjson/{path.name}")
    bad = set(r.sample_idx(len(records), int(round(len(records) * malformed_rate))).tolist())
    malformed = 0
    with open(path, "w", encoding="utf-8") as f:
        for i, rec in enumerate(records):
            # sparse encoding: producers omit keys that carry no value
            line = json.dumps(
                {k: v for k, v in rec.items() if v is not None}, default=str, separators=(",", ":")
            )
            if i in bad:
                kind = int(r.ints(0, 3))
                if kind == 0:
                    line = line[: max(5, len(line) // 2)]  # truncated
                elif kind == 1:
                    line = "<<<producer restart>>>"  # non-JSON garbage
                else:
                    line = line.replace('"event_type":', '"event_type"')  # broken syntax
                malformed += 1
            f.write(line + "\n")
    return len(records), malformed


def write_log(df: pd.DataFrame, path: Path, rng: Rng, malformed_rate: float = 0.0) -> tuple[int, int]:
    path.parent.mkdir(parents=True, exist_ok=True)
    r = rng.child(f"log/{path.name}")
    bad = set(r.sample_idx(len(df), int(round(len(df) * malformed_rate))).tolist())
    malformed = 0
    with open(path, "w", encoding="utf-8") as f:
        f.write("# shipping-tracker event log | SYNTHETIC DATA generated by DataForge\n")
        for i, row in enumerate(df.to_dict("records")):
            line = render_log_line(row)
            if i in bad:
                kind = int(r.ints(0, 3))
                if kind == 0:
                    line = line[:40]
                elif kind == 1:
                    line = (
                        f"{row['event_ts']} ERROR [shipping-tracker] tracker restarted, event buffer flushed"
                    )
                else:
                    line = line.replace(" event=", " evnt=")  # required key missing
                malformed += 1
            f.write(line + "\n")
    return len(df), malformed
