#!/usr/bin/env python
"""Render the rule catalogue and warehouse checks to docs/data_quality_rules.md.

Keeping the document generated means it cannot drift from the code.

    python scripts/export_quality_rules.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from dataforge.quality.suites import SUITES  # noqa: E402
from dataforge.quality.warehouse_checks import CHECKS, freshness_checks  # noqa: E402

OUT = Path(__file__).resolve().parent.parent / "docs" / "data_quality_rules.md"

CHECK_DESCRIPTIONS = {
    "not_null": "value must be present",
    "regex": "value must match a pattern",
    "in_set": "value must be one of an allowed set",
    "castable": "the raw string must convert to the target type",
    "compare": "value compared against a constant",
    "compare_cols": "two columns compared",
    "not_future": "timestamp must not be after the reference timestamp",
    "fk": "value must exist in a reference dataset",
    "expr": "arbitrary SQL boolean expression",
}


def main() -> int:
    lines: list[str] = []
    a = lines.append
    a("<!-- GENERATED by scripts/export_quality_rules.py - do not edit by hand. -->")
    a("# Data quality rule catalogue\n")
    total = sum(len(s.rules) for s in SUITES.values())
    a(f"{total} row-level rules across {len(SUITES)} datasets, plus {len(CHECKS) + len(freshness_checks('YYYY-MM-DD'))} warehouse-level checks.\n")
    a("**Severity**\n")
    a("| Severity | Effect |")
    a("|---|---|")
    a("| `reject` | The row is written to quarantine with its rule ids and error messages; it never reaches silver. |")
    a("| `warn` | The row is kept; the rule id is appended to its `quality_warnings` array and counted in `monitoring.quality_results`. |\n")
    a("**Check types**\n")
    a("| Check | Meaning |")
    a("|---|---|")
    for k, v in CHECK_DESCRIPTIONS.items():
        a(f"| `{k}` | {v} |")
    a("")
    a("Columns suffixed `_t` are typed casts of the raw string and `_n` are normalised strings, both computed by the silver job before validation.\n")
    a("## Circuit breakers (max reject rate per dataset)\n")
    a("| Dataset | Max reject rate | Rationale |")
    a("|---|---|---|")
    for name, s in SUITES.items():
        rationale = "child dataset - inherits rejections from its parent, so the budget is wider" if s.max_reject_rate > 0.05 else "primary dataset - a higher rate means the source is broken"
        a(f"| `{name}` | {s.max_reject_rate:.0%} | {rationale} |")
    a("\nExceeding the rate raises `QualityThresholdError` and aborts the run before anything is published.\n")

    for name, suite in SUITES.items():
        a(f"## `{name}`\n")
        if suite.description:
            a(f"{suite.description}\n")
        a("| Rule id | Severity | Check | Column | Rule | Why |")
        a("|---|---|---|---|---|---|")
        for r in suite.rules:
            params = ""
            if r.check == "regex":
                params = f" `{r.params['pattern']}`"
            elif r.check == "in_set":
                params = " " + ", ".join(f"`{v}`" for v in r.params["values"])
            elif r.check == "compare":
                params = f" `{r.params['op']} {r.params['value']}`"
            elif r.check == "compare_cols":
                params = f" `{r.params['left']} {r.params['op']} {r.params['right']}`"
            elif r.check == "fk":
                params = f" -> `{r.params['ref']}.{r.params['ref_column']}`"
            elif r.check == "expr":
                params = f" `{r.params['expression']}`"
            col = f"`{r.column}`" if r.column else "-"
            a(f"| `{r.id}` | {r.severity} | `{r.check}` | {col} | {r.description}{params} | {r.rationale or '-'} |")
        a("")

    a("## Warehouse checks (after loading PostgreSQL)\n")
    a("| Check id | Severity | Table | Rule | Max failure rate |")
    a("|---|---|---|---|---|")
    for c in CHECKS + freshness_checks("YYYY-MM-DD"):
        a(f"| `{c.id}` | {c.severity} | `{c.table}` | {c.description} | {c.max_failure_rate:.0%} |")
    a("")
    a("A failing `error` check aborts the run (nothing is published); a failing `warn` check is recorded and shown on the dashboard.\n")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} ({total} rules)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
