"""The rule catalogue: every validation rule applied in the silver layer.

Naming: <dataset>.<rule>. Columns ending in `_t` are typed casts of the raw string
column and columns ending in `_n` are normalised strings, both produced by the silver
job before validation (see dataforge/spark/silver/common.py).

`python scripts/export_quality_rules.py` renders this catalogue to docs/data_quality_rules.md.
"""

from __future__ import annotations

from .rules import Rule, RuleSuite

ORDER_STATUSES = ["placed", "paid", "shipped", "delivered", "cancelled", "returned"]
CHANNELS = ["web", "mobile_app", "marketplace", "store"]
CURRENCIES = ["USD", "CAD", "EUR", "GBP", "SEK", "INR", "SGD", "AUD", "BRL", "AED"]
PAYMENT_METHODS = ["credit_card", "debit_card", "wallet", "bank_transfer", "cash_on_delivery", "refund"]
PAYMENT_STATUSES = ["captured", "failed", "refunded", "authorized"]
SEGMENTS = ["consumer", "business", "vip"]
INVENTORY_EVENT_TYPES = ["receipt", "shipment", "adjustment", "return", "stock_count"]
SHIPPING_EVENTS = [
    "label_created",
    "picked_up",
    "in_transit",
    "out_for_delivery",
    "delivered",
    "delivery_exception",
    "returned",
]
EMAIL_RE = r"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$"


def R(id_, dataset, check, severity, description, column=None, rationale="", **params) -> Rule:
    return Rule(
        id=id_,
        dataset=dataset,
        check=check,
        severity=severity,
        description=description,
        column=column,
        params=params,
        rationale=rationale,
    )


CUSTOMERS = RuleSuite(
    dataset="customers",
    description="Customer master from the CRM export.",
    max_reject_rate=0.05,
    rules=[
        R(
            "customers.customer_id_not_null",
            "customers",
            "not_null",
            "reject",
            "customer_id is required",
            "customer_id",
            "Primary business key; rows without it cannot be matched to orders.",
        ),
        R(
            "customers.customer_id_format",
            "customers",
            "regex",
            "reject",
            "customer_id must look like CUST-000000",
            "customer_id",
            pattern=r"^CUST-\d{6}$",
        ),
        R(
            "customers.email_format",
            "customers",
            "regex",
            "warn",
            "email is not a valid address (set to NULL)",
            "email_n",
            pattern=EMAIL_RE,
            rationale="A bad contact field must not erase the customer's order history; the value is nulled and reported.",
        ),
        R("customers.email_present", "customers", "not_null", "warn", "email is missing", "email_n"),
        R(
            "customers.signup_date_valid",
            "customers",
            "castable",
            "warn",
            "signup_date is not a valid date (set to NULL)",
            "signup_date",
            typed="signup_date_t",
        ),
        R(
            "customers.signup_date_not_future",
            "customers",
            "not_future",
            "warn",
            "signup_date is in the future (set to NULL)",
            "signup_date_t",
        ),
        R(
            "customers.updated_at_valid",
            "customers",
            "castable",
            "reject",
            "updated_at must be a valid timestamp",
            "updated_at",
            typed="updated_at_t",
        ),
        R(
            "customers.segment_allowed",
            "customers",
            "in_set",
            "reject",
            "customer_segment must be consumer|business|vip",
            "customer_segment_n",
            values=SEGMENTS,
        ),
        R(
            "customers.region_known",
            "customers",
            "fk",
            "reject",
            "region_code must exist in the regions reference",
            "region_code",
            ref="regions",
            ref_column="region_code",
        ),
        R(
            "customers.country_recognised",
            "customers",
            "not_null",
            "warn",
            "country could not be mapped to an ISO code",
            "country_code_n",
            rationale="Unknown spellings are kept (country_code NULL) and reported so the alias map can be extended.",
        ),
        R(
            "customers.birth_date_valid",
            "customers",
            "castable",
            "warn",
            "birth_date is not a valid date (set to NULL)",
            "birth_date",
            typed="birth_date_t",
        ),
    ],
)

PRODUCTS = RuleSuite(
    dataset="products",
    description="Product catalog feed (JSON).",
    rules=[
        R(
            "products.product_id_not_null",
            "products",
            "not_null",
            "reject",
            "product_id is required",
            "product_id",
        ),
        R(
            "products.product_id_format",
            "products",
            "regex",
            "reject",
            "product_id must look like PRD-00000",
            "product_id",
            pattern=r"^PRD-\d{5}$",
        ),
        R(
            "products.unit_price_not_null",
            "products",
            "not_null",
            "reject",
            "unit_price is required",
            "unit_price",
        ),
        R(
            "products.unit_price_numeric",
            "products",
            "castable",
            "reject",
            "unit_price must be numeric",
            "unit_price",
            typed="unit_price_t",
            rationale="Strings such as '$12.99' are a type violation from the producer, not a pricing decision.",
        ),
        R(
            "products.unit_price_positive",
            "products",
            "compare",
            "reject",
            "unit_price must be greater than zero",
            "unit_price_t",
            op=">",
            value=0,
        ),
        R(
            "products.unit_cost_numeric",
            "products",
            "castable",
            "reject",
            "unit_cost must be numeric",
            "unit_cost",
            typed="unit_cost_t",
        ),
        R(
            "products.unit_cost_non_negative",
            "products",
            "compare",
            "reject",
            "unit_cost must be >= 0",
            "unit_cost_t",
            op=">=",
            value=0,
        ),
        R(
            "products.margin_non_negative",
            "products",
            "compare_cols",
            "warn",
            "unit_cost exceeds unit_price (negative margin)",
            None,
            left="unit_cost_t",
            op="<=",
            right="unit_price_t",
        ),
        R(
            "products.category_known",
            "products",
            "fk",
            "reject",
            "category_id must exist in categories",
            "category_id",
            ref="categories",
            ref_column="category_id",
        ),
        R(
            "products.supplier_known",
            "products",
            "fk",
            "reject",
            "supplier_id must exist in suppliers",
            "supplier_id",
            ref="suppliers",
            ref_column="supplier_id",
        ),
        R(
            "products.currency_allowed",
            "products",
            "in_set",
            "reject",
            "currency must be a supported ISO code",
            "currency_n",
            values=CURRENCIES,
        ),
        R(
            "products.is_active_boolean",
            "products",
            "castable",
            "reject",
            "is_active must be boolean",
            "is_active",
            typed="is_active_t",
        ),
        R(
            "products.updated_at_valid",
            "products",
            "castable",
            "reject",
            "updated_at must be a valid timestamp",
            "updated_at",
            typed="updated_at_t",
        ),
        R(
            "products.dimensions_parseable",
            "products",
            "expr",
            "warn",
            "dimensions_cm is not a JSON object (dimensions set to NULL)",
            None,
            expression="dimensions_cm IS NULL OR length_cm_t IS NOT NULL",
        ),
    ],
)

ORDERS = RuleSuite(
    dataset="orders",
    description="Order headers from the OMS export.",
    rules=[
        R("orders.order_id_not_null", "orders", "not_null", "reject", "order_id is required", "order_id"),
        R(
            "orders.order_id_format",
            "orders",
            "regex",
            "reject",
            "order_id must look like ORD-0000000",
            "order_id",
            pattern=r"^ORD-\d{7}$",
        ),
        R(
            "orders.customer_known",
            "orders",
            "fk",
            "reject",
            "customer_id must exist in silver customers",
            "customer_id",
            ref="customers",
            ref_column="customer_id",
            rationale="Orphan orders cannot be attributed; they are quarantined until the customer record arrives.",
        ),
        R(
            "orders.order_date_not_null",
            "orders",
            "not_null",
            "reject",
            "order_date is required",
            "order_date",
        ),
        R(
            "orders.order_date_valid",
            "orders",
            "castable",
            "reject",
            "order_date must be a valid timestamp",
            "order_date",
            typed="order_date_t",
        ),
        R(
            "orders.order_date_not_future",
            "orders",
            "not_future",
            "reject",
            "order_date must not be after ingestion time",
            "order_date_t",
        ),
        R(
            "orders.status_allowed",
            "orders",
            "in_set",
            "reject",
            "status must be one of the known order states",
            "status_n",
            values=ORDER_STATUSES,
        ),
        R(
            "orders.currency_allowed",
            "orders",
            "in_set",
            "reject",
            "currency must be a supported ISO code",
            "currency_n",
            values=CURRENCIES,
        ),
        R(
            "orders.order_total_numeric",
            "orders",
            "castable",
            "reject",
            "order_total must be numeric",
            "order_total",
            typed="order_total_t",
        ),
        R(
            "orders.order_total_non_negative",
            "orders",
            "compare",
            "reject",
            "order_total must be >= 0",
            "order_total_t",
            op=">=",
            value=0,
        ),
        R(
            "orders.updated_at_valid",
            "orders",
            "castable",
            "reject",
            "updated_at must be a valid timestamp",
            "updated_at",
            typed="updated_at_t",
        ),
        R(
            "orders.channel_allowed",
            "orders",
            "in_set",
            "warn",
            "channel is not a known sales channel",
            "channel_n",
            values=CHANNELS,
        ),
        R(
            "orders.region_present",
            "orders",
            "not_null",
            "warn",
            "region_code missing (derived from the customer)",
            "region_code_n",
        ),
    ],
)

# Child datasets inherit rejections from their parents (an order in quarantine takes its
# lines, payments and shipping events with it), so their circuit breaker is looser.
CASCADE_MAX_REJECT_RATE = 0.10

ORDER_ITEMS = RuleSuite(
    dataset="order_items",
    description="Order lines from the OMS export.",
    max_reject_rate=CASCADE_MAX_REJECT_RATE,
    rules=[
        R(
            "order_items.order_item_id_not_null",
            "order_items",
            "not_null",
            "reject",
            "order_item_id is required",
            "order_item_id",
        ),
        R(
            "order_items.order_known",
            "order_items",
            "fk",
            "reject",
            "order_id must exist in silver orders",
            "order_id",
            ref="orders",
            ref_column="order_id",
            broadcast=False,
            rationale="Lines of a quarantined order are quarantined too (cascade) so facts never partially reflect an order.",
        ),
        R(
            "order_items.product_known",
            "order_items",
            "fk",
            "reject",
            "product_id must exist in silver products",
            "product_id",
            ref="products",
            ref_column="product_id",
        ),
        R(
            "order_items.quantity_not_null",
            "order_items",
            "not_null",
            "reject",
            "quantity is required",
            "quantity",
        ),
        R(
            "order_items.quantity_integer",
            "order_items",
            "castable",
            "reject",
            "quantity must be an integer",
            "quantity",
            typed="quantity_t",
        ),
        R(
            "order_items.quantity_positive",
            "order_items",
            "compare",
            "reject",
            "quantity must be greater than zero",
            "quantity_t",
            op=">",
            value=0,
        ),
        R(
            "order_items.unit_price_numeric",
            "order_items",
            "castable",
            "reject",
            "unit_price must be numeric",
            "unit_price",
            typed="unit_price_t",
        ),
        R(
            "order_items.unit_price_positive",
            "order_items",
            "compare",
            "reject",
            "unit_price must be greater than zero",
            "unit_price_t",
            op=">",
            value=0,
        ),
        R(
            "order_items.discount_range",
            "order_items",
            "expr",
            "reject",
            "discount_pct must be between 0 and 100",
            None,
            expression="discount_pct_t IS NULL OR (discount_pct_t >= 0 AND discount_pct_t <= 100)",
        ),
        R(
            "order_items.line_total_numeric",
            "order_items",
            "castable",
            "reject",
            "line_total must be numeric",
            "line_total",
            typed="line_total_t",
        ),
        R(
            "order_items.line_total_consistent",
            "order_items",
            "expr",
            "warn",
            "line_total differs from quantity*unit_price*(1-discount) by more than 0.05 (recomputed)",
            None,
            expression="ABS(line_total_t - line_total_calc) <= 0.05",
        ),
    ],
)

PAYMENTS = RuleSuite(
    dataset="payments",
    description="Payment transactions.",
    max_reject_rate=CASCADE_MAX_REJECT_RATE,
    rules=[
        R(
            "payments.payment_id_not_null",
            "payments",
            "not_null",
            "reject",
            "payment_id is required",
            "payment_id",
        ),
        R(
            "payments.order_known",
            "payments",
            "fk",
            "reject",
            "order_id must exist in silver orders",
            "order_id",
            ref="orders",
            ref_column="order_id",
            broadcast=False,
        ),
        R(
            "payments.method_allowed",
            "payments",
            "in_set",
            "reject",
            "payment_method is not a supported method",
            "payment_method_n",
            values=PAYMENT_METHODS,
        ),
        R(
            "payments.status_allowed",
            "payments",
            "in_set",
            "reject",
            "status must be captured|failed|refunded|authorized",
            "status_n",
            values=PAYMENT_STATUSES,
        ),
        R(
            "payments.amount_numeric",
            "payments",
            "castable",
            "reject",
            "amount must be numeric",
            "amount",
            typed="amount_t",
        ),
        R("payments.paid_at_not_null", "payments", "not_null", "reject", "paid_at is required", "paid_at"),
        R(
            "payments.paid_at_valid",
            "payments",
            "castable",
            "reject",
            "paid_at must be a valid timestamp",
            "paid_at",
            typed="paid_at_t",
        ),
        R(
            "payments.amount_matches_order",
            "payments",
            "expr",
            "warn",
            "captured amount differs from the order total",
            None,
            expression="status_n <> 'captured' OR order_total_ref IS NULL OR ABS(amount_t - order_total_ref) <= 0.05",
        ),
    ],
)

INVENTORY_EVENTS = RuleSuite(
    dataset="inventory_events",
    description="Warehouse inventory event stream.",
    rules=[
        R(
            "inventory_events.event_id_not_null",
            "inventory_events",
            "not_null",
            "reject",
            "event_id is required",
            "event_id",
        ),
        R(
            "inventory_events.event_type_allowed",
            "inventory_events",
            "in_set",
            "reject",
            "event_type must be receipt|shipment|adjustment|return|stock_count",
            "event_type_n",
            values=INVENTORY_EVENT_TYPES,
        ),
        R(
            "inventory_events.product_known",
            "inventory_events",
            "fk",
            "reject",
            "product_id must exist in silver products",
            "product_id",
            ref="products",
            ref_column="product_id",
        ),
        R(
            "inventory_events.warehouse_known",
            "inventory_events",
            "fk",
            "reject",
            "warehouse_id must exist in warehouses",
            "warehouse_id",
            ref="warehouses",
            ref_column="warehouse_id",
        ),
        R(
            "inventory_events.quantity_delta_not_null",
            "inventory_events",
            "not_null",
            "reject",
            "quantity_delta is required",
            "quantity_delta",
        ),
        R(
            "inventory_events.quantity_delta_integer",
            "inventory_events",
            "castable",
            "reject",
            "quantity_delta must be an integer",
            "quantity_delta",
            typed="quantity_delta_t",
        ),
        R(
            "inventory_events.event_ts_not_null",
            "inventory_events",
            "not_null",
            "reject",
            "event_ts is required",
            "event_ts",
        ),
        R(
            "inventory_events.event_ts_valid",
            "inventory_events",
            "castable",
            "reject",
            "event_ts must be a valid timestamp",
            "event_ts",
            typed="event_ts_t",
        ),
        R(
            "inventory_events.event_ts_not_future",
            "inventory_events",
            "not_future",
            "reject",
            "event_ts must not be after ingestion time",
            "event_ts_t",
        ),
        R(
            "inventory_events.sign_matches_type",
            "inventory_events",
            "expr",
            "reject",
            "receipts/returns must be >= 0 and shipments <= 0",
            None,
            expression="(event_type_n IN ('receipt','return') AND quantity_delta_t >= 0) OR (event_type_n = 'shipment' AND quantity_delta_t <= 0) OR event_type_n IN ('adjustment','stock_count') OR event_type_n IS NULL OR quantity_delta_t IS NULL",
            rationale="A negative receipt is almost always a producer bug; letting it through would corrupt on-hand stock.",
        ),
        R(
            "inventory_events.defective_within_received",
            "inventory_events",
            "expr",
            "warn",
            "defective_qty exceeds received quantity",
            None,
            expression="defective_qty_t IS NULL OR quantity_delta_t IS NULL OR defective_qty_t <= quantity_delta_t",
        ),
    ],
)

SHIPPING_EVENTS = RuleSuite(
    dataset="shipping_events",
    description="Shipping tracker log events.",
    max_reject_rate=CASCADE_MAX_REJECT_RATE,
    rules=[
        R(
            "shipping_events.event_ts_not_null",
            "shipping_events",
            "not_null",
            "reject",
            "event_ts is required",
            "event_ts",
        ),
        R(
            "shipping_events.event_ts_valid",
            "shipping_events",
            "castable",
            "reject",
            "event_ts must be a valid timestamp",
            "event_ts",
            typed="event_ts_t",
        ),
        R(
            "shipping_events.event_allowed",
            "shipping_events",
            "in_set",
            "reject",
            "event must be a known tracker event",
            "event_n",
            values=SHIPPING_EVENTS,
        ),
        R(
            "shipping_events.shipment_id_format",
            "shipping_events",
            "regex",
            "reject",
            "shipment_id must look like SHP-0000000",
            "shipment_id",
            pattern=r"^SHP-\d{7}$",
        ),
        R(
            "shipping_events.order_id_not_null",
            "shipping_events",
            "not_null",
            "reject",
            "order_id is required",
            "order_id_n",
        ),
        R(
            "shipping_events.order_known",
            "shipping_events",
            "fk",
            "reject",
            "order_id must exist in silver orders",
            "order_id_n",
            ref="orders",
            ref_column="order_id",
            broadcast=False,
        ),
        R(
            "shipping_events.warehouse_known",
            "shipping_events",
            "fk",
            "warn",
            "warehouse_id is not a known warehouse",
            "warehouse_id",
            ref="warehouses",
            ref_column="warehouse_id",
        ),
        R(
            "shipping_events.carrier_present",
            "shipping_events",
            "not_null",
            "warn",
            "carrier is missing",
            "carrier",
        ),
    ],
)

SUITES: dict[str, RuleSuite] = {
    s.dataset: s
    for s in (CUSTOMERS, PRODUCTS, ORDERS, ORDER_ITEMS, PAYMENTS, INVENTORY_EVENTS, SHIPPING_EVENTS)
}
